name: AngelSkySkyblock
version: 1.0.0
main: fr.angelsky.skyblock.Skyblock
api-version: 1.18
authors: [ Ariouz ]
website: https://angelsky.fr
depend:
  - Vault
  - AngelskyApi
  - SkyblockAPI
  - AngelSkyEconomy
commands:
  lobby:
    description: Retourner au lobby
    aliases: [hub]
  spawn:
    description: Teleporter au spawn
  menu:
    description: Ouvre le menu Principal
  voteparty:
    description: Commande VoteParty
  playerlevel:
    description: Commande PlayerLevel
  discord:
    description: Serveur Discord
  vote:
    description: Lien pour voter
    aliases:
      - voter
  boutique:
    description: Lien de la boutique du serveur
  niveaux:
    description: Menu des niveaux
    aliases:
      - niveau
  shop:
    description: Menu du shop
  upgradetokens:
    description: Commande UpgradeTokens
  cratekey:
    description: Permet de give une/des clé(s) de caisse à un joueur / tous les joueurs
  eglow:
    description: Ouvre le menu des surbrillances
  poubelle:
    description: Ouvre un menu pour jeter ses items non utilisés
    aliases:
      - trash

